name: ci_meson

on:
  # Allow manual workflow triggering
  workflow_dispatch:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.y"
      - "**.l"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.y"
      - "**.l"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        brew install gcc clang-format
        brew install flex bison
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

        echo 'export PATH="/opt/homebrew/opt/bison/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PATH="/opt/homebrew/opt/flex/bin:$PATH"' >> $GITHUB_ENV

        export LDFLAGS="-L/opt/homebrew/opt/bison/lib"
        export LDFLAGS="-L/opt/homebrew/opt/flex/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/flex/include"
    - name: Check toolchain versions
      run: |
        echo "GCC version:"
        gcc --version
        echo "Flex version:"
        flex --version
        echo "Bison version:"
        bison --version
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v
    - run: ninja -C builddir clang-format-check
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
